layout_spectrum: 1
color:
  saturation: 0.4268152
  brandStrength: 0.3984115
  lightness: 0.481346
  rhythmicContrast: 0.9070892
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 1
name: PhotosByMAC
